# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb2/admin/helloworld.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb2.admin import user_pb2 as pb2_dot_admin_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apb2/admin/helloworld.proto\x12\tpb2.admin\x1a\x14pb2/admin/user.proto\"\"\n\x0cHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"K\n\nHelloReply\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12#\n\x04user\x18\x02 \x01(\x0b\x32\x0f.pb2.admin.UserR\x04user2G\n\x07Greeter\x12<\n\x08SayHello\x12\x17.pb2.admin.HelloRequest\x1a\x15.pb2.admin.HelloReply\"\x00\x42\rZ\x0b./pb2_adminb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb2.admin.helloworld_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./pb2_admin'
  _globals['_HELLOREQUEST']._serialized_start=63
  _globals['_HELLOREQUEST']._serialized_end=97
  _globals['_HELLOREPLY']._serialized_start=99
  _globals['_HELLOREPLY']._serialized_end=174
  _globals['_GREETER']._serialized_start=176
  _globals['_GREETER']._serialized_end=247
# @@protoc_insertion_point(module_scope)
