# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb2.third import helloworld_pb2 as pb2_dot_third_dot_helloworld__pb2


class GreeterStub(object):
    """定義服務
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/pb2.third.Greeter/SayHello',
                request_serializer=pb2_dot_third_dot_helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=pb2_dot_third_dot_helloworld__pb2.HelloReply.FromString,
                )


class GreeterServicer(object):
    """定義服務
    """

    def SayHello(self, request, context):
        """傳入 HelloRequest，回傳 HelloReply
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=pb2_dot_third_dot_helloworld__pb2.HelloRequest.FromString,
                    response_serializer=pb2_dot_third_dot_helloworld__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb2.third.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """定義服務
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb2.third.Greeter/SayHello',
            pb2_dot_third_dot_helloworld__pb2.HelloRequest.SerializeToString,
            pb2_dot_third_dot_helloworld__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
