# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb2/app/helloworld.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb2.app import user_pb2 as pb2_dot_app_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18pb2/app/helloworld.proto\x12\x07pb2.app\x1a\x12pb2/app/user.proto\"\"\n\x0cHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"I\n\nHelloReply\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12!\n\x04user\x18\x02 \x01(\x0b\x32\r.pb2.app.UserR\x04user2C\n\x07Greeter\x12\x38\n\x08SayHello\x12\x15.pb2.app.HelloRequest\x1a\x13.pb2.app.HelloReply\"\x00\x42\x0bZ\t./pb2_appb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb2.app.helloworld_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./pb2_app'
  _globals['_HELLOREQUEST']._serialized_start=57
  _globals['_HELLOREQUEST']._serialized_end=91
  _globals['_HELLOREPLY']._serialized_start=93
  _globals['_HELLOREPLY']._serialized_end=166
  _globals['_GREETER']._serialized_start=168
  _globals['_GREETER']._serialized_end=235
# @@protoc_insertion_point(module_scope)
